packages:
  - 'apps/backend'
  - 'apps/web-shell'
  - 'apps/auth-mf'
  - 'apps/dashboard-mf'
  - 'apps/menu-mf'
  - 'apps/orders-mf'
  - 'apps/kitchen-mf'
  - 'apps/cashier-mf'
  - 'apps/reports-mf'
  - 'apps/reservations-mf'
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
